### ISSUE TITLE
URL bar autocomplete is annoying

### ISSUE THREAD

**Issue by suhr** [browserhtml/browserhtml#1164] opened 2016-07-02 21:16 UTC
When you press arrow key (←) to fix a typo it makes completed text persistent so you have to remove it.
Then you type text in the middle of word, it autocompletes the end.
Also it blinks while it really should not to.

Servo/browserhtml: nightly build.

Additional info: Yandex is a good example how proper autocomplete looks like. Everything is instant, completion is grey and becomes a text only when you push → or Tab.

Moved from https://github.com/servo/servo/issues/12174.

**Comment by Gozala** [comment] 2016-07-05 23:07
Thanks for the feedback @suhr you are right current behavior is annoying, as it requires double backspace key per each character & it will be resolved by #1167

As of blinks that is unexpected, can you provide more details on that ?

**Comment by suhr** [comment] 2016-07-05 23:40
> As of blinks that is unexpected, can you provide more details on that ?

1. You have something autcompleted in the URL bar
2. You type more
3. Autocomplete text disappears
4. Since autocomplete is not instant, showing next autocompete looks like blink

Autocomplete really should not be just selected text (again, just look at yandex).

**Comment by Gozala** [comment] 2016-07-06 00:07
@suhr I understand you like the way yandex autocomplete works. We might in fact move to something along those lines. That being said current behavior is by design, so until we change the design I don't think there is much value in keeping this issue open (For updates on delete please subscribe to #1167).

As of flickering you have the same behavior on yandex, it's just due to faded completion it's less visible.

P.S.: Current behavior uses selected completion explicitly so that user won't need to press `ArrowRight` to navigate to the top suggestion.

**Closed by Gozala** 2016-07-06 00:07 UTC
