### ISSUE TITLE
white screen and no loading when using --browserhtml flag

### ISSUE THREAD

**Issue by Jayflux** [browserhtml/browserhtml#966] opened 2016-03-28 11:28 UTC
http://imgur.com/6KSKzwu

Any idea why i get this?
Thanks

**Comment by paulrouget** [comment] 2016-03-28 11:39
does any page render properly with `-b` and `-w`? For example:

`./mach run -- -b -w http://firefox.com`

**Comment by Jayflux** [comment] 2016-03-28 18:50
@paulrouget 

```
Jason@DESKTOP-P2J3G0V MINGW64 ~/servo
$ ./mach run -- -b -w http://firefox.com
You have multiple profiles built. Please specify which one to run with '--release' or '--dev'.

Jason@DESKTOP-P2J3G0V MINGW64 ~/servo
$ ./mach run -r -- -b -w http://firefox.com
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\quad.vs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\quad.fs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\blit.vs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\blit.fs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\border.vs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\border.fs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\blend.vs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\blend.fs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\filter.vs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\filter.fs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\box_shadow.vs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\box_shadow.fs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\blur.vs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\blur.fs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\mask.vs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\mask.fs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\debug_font.vs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\debug_font.fs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\debug_color.vs.glsl"
compile "\\\\?\\C:\\msys64\\home\\Jason\\servo\\resources\\shaders\\debug_color.fs.glsl"
thread '<unnamed>' panicked at 'Didn't find a cached resource with that ID!', ../src/libcore\option.rs:704
stack backtrace:
   0:          0x211f00a - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43536
   1:          0x211e53e - panicking::default_handler::hcbd606cfbd8bf50bKsA
   2:          0x20e1bef - sys_common::unwind::begin_unwind_inner::hbdeeb049085a1e58RRt
   3:          0x20e31eb - sys_common::unwind::begin_unwind_fmt::h6f77f0426d82c98bXQt
   4:          0x2110ff2 - rust_begin_unwind
   5:          0x21335e8 - panicking::panic_fmt::h769e276b1a4fb549FRL
   6:          0x2154074 - option::expect_failed::h9c786e256c8d339fLpO
   7:          0x115b6d8 - resource_cache::ResourceCache::get_glyph::h8eee30ee1d490ae40Jp
   8:          0x10de275 - node_compiler::AABBTreeNode.NodeCompiler::compile::hf1d286662ae4f720FCo
   9:          0x10c24d1 - F.FnBox::call_box::h17666168949236633713
  10:          0x14febe2 - sys_common::unwind::try::try_fn::h2156444792690681502
  11:          0x2110f1a - sys_common::unwind::inner_try::h77626a58c53b5bb4TOt
  12:          0x15024fe - boxed::F.FnBox<A>::call_box::h17550217279392065921
  13:          0x211c499 - sys::thread::Thread::new::thread_start::h7d995f17b3b89feeazz
  14:     0x7ff859082d91 - GLOBAL__sub_I__ZN15GrGLConicEffectC2ERK22GrBackendEffectFactoryRK12GrDrawEffect
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore\result.rs:746
stack backtrace:
   0:          0x211f00a - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43536
   1:          0x211e53e - panicking::default_handler::hcbd606cfbd8bf50bKsA
   2:          0x20e1bef - sys_common::unwind::begin_unwind_inner::hbdeeb049085a1e58RRt
   3:          0x20e31eb - sys_common::unwind::begin_unwind_fmt::h6f77f0426d82c98bXQt
   4:          0x2110ff2 - rust_begin_unwind
   5:          0x21335e8 - panicking::panic_fmt::h769e276b1a4fb549FRL
   6:          0x1508e72 - result::unwrap_failed::h6588446062173913304
   7:          0x1507f36 - Scope<'pool, 'scope>::join_all::hf405d1ea2db018eeaga
   8:          0x10bc7d7 - frame::Frame::build::h83e74345ca81458dWIk
   9:          0x11226bc - render_backend::RenderBackend::render::h879ce7679bd442fbarp
  10:          0x10ec24b - render_backend::RenderBackend::run::hc7e1599b5d9433e6xgp
  11:          0x10c9246 - sys_common::unwind::try::try_fn::h6470807034771693439
  12:          0x2110f1a - sys_common::unwind::inner_try::h77626a58c53b5bb4TOt
  13:          0x10c971a - boxed::F.FnBox<A>::call_box::h5139817102405960911
  14:          0x211c499 - sys::thread::Thread::new::thread_start::h7d995f17b3b89feeazz
  15:     0x7ff859082d91 - GLOBAL__sub_I__ZN15GrGLConicEffectC2ERK22GrBackendEffectFactoryRK12GrDrawEffect
thread 'LayoutThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: BrokenPipe, error: StringError("MPSC channel closed") }) }', ../src/libcore\result.rs:746
stack backtrace:
   0:          0x211f00a - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43536
   1:          0x211e53e - panicking::default_handler::hcbd606cfbd8bf50bKsA
   2:          0x20e1bef - sys_common::unwind::begin_unwind_inner::hbdeeb049085a1e58RRt
   3:          0x20e31eb - sys_common::unwind::begin_unwind_fmt::h6f77f0426d82c98bXQt
   4:          0x2110ff2 - rust_begin_unwind
   5:          0x21335e8 - panicking::panic_fmt::h769e276b1a4fb549FRL
   6:          0x176d2e0 - result::unwrap_failed::h11194660588153814913
   7:          0x177fd69 - api::RenderApi::set_root_stacking_context::h1807bcae9f44c95ezTb
   8:           0x6731e1 - layout_thread::LayoutThread::perform_post_main_layout_passes::hfa75d3960cde4ad7I3r
   9:           0x61ed6e - layout_thread::LayoutThread::perform_post_style_recalc_layout_passes::h59ea403ea6fd2ee23Zr
  10:           0x5ef3c1 - layout_thread::LayoutThread::handle_request::h0f268e1c3360bb7aKar
  11:           0x5b3c4a - sys_common::unwind::try::try_fn::h6604567348182126160
  12:          0x2110f1a - sys_common::unwind::inner_try::h77626a58c53b5bb4TOt
  13:           0x5b469a - boxed::F.FnBox<A>::call_box::h1271840612883691927
  14:          0x211c499 - sys::thread::Thread::new::thread_start::h7d995f17b3b89feeazz
  15:     0x7ff859082d91 - GLOBAL__sub_I__ZN15GrGLConicEffectC2ERK22GrBackendEffectFactoryRK12GrDrawEffect
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', ../src/libcore\result.rs:746
thread 'PaintThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore\result.rs:746
thread 'LayoutWorker worker 1/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore\result.rs:746
thread 'LayoutWorker worker 2/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore\result.rs:746
thread 'LayoutWorker worker 3/3' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore\result.rs:746
thread 'Constellation' panicked at 'unable to find pipeline - this is a bug', ../src/libcore\option.rs:704
stack backtrace:
   0:          0x211f00a - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43536
   1:          0x211e53e - panicking::default_handler::hcbd606cfbd8bf50bKsA
   2:          0x20e1bef - sys_common::unwind::begin_unwind_inner::hbdeeb049085a1e58RRt
   3:          0x20e31eb - sys_common::unwind::begin_unwind_fmt::h6f77f0426d82c98bXQt
   4:          0x2110ff2 - rust_begin_unwind
   5:          0x21335e8 - panicking::panic_fmt::h769e276b1a4fb549FRL
   6:           0x72d682 - result::unwrap_failed::h7496856826199683403
   7:           0x7324b5 - query::LayoutRPCImpl.LayoutRPC::resolved_style::h37f83b448d62961cStt
   8:           0xd8633c - dom::window::Window::resolved_style_query::h70ec86ceb1c08be5Upo
   9:           0x755ebf - dom::cssstyledeclaration::CSSStyleDeclaration.CSSStyleDeclarationMethods::GetPropertyValue::h03b861189a5fb56a3MK
  10:           0x78b97b - dom::bindings::codegen::Bindings::CSSStyleDeclarationBinding::get_top::h7c21446511039d41FOx
  11:          0x17dc2b7 - CallJitGetterOp
  12:           0xc24ac8 - dom::bindings::utils::generic_call::h68dbfb4247502582cqg
  13:           0xc24c57 - dom::bindings::utils::generic_getter::hc0b3b04d93df8017aug
  14:          0x1947270 - ZN2js6InvokeEP9JSContextN2JS8CallArgsENS_14MaybeConstructE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jscntxtinlines.h:235
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:502
  15:          0x19484a2 - ZN2js6InvokeEP9JSContextRKN2JS5ValueES5_jPS4_NS2_13MutableHandleIS3_EE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:558
  16:          0x194b89b - ZN2js20InvokeGetterOrSetterEP9JSContextP8JSObjectN2JS5ValueEjPS5_NS4_13MutableHandleIS5_EE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:628
  17:          0x1951112 - ZL10CallGetterP9JSContextN2JS6HandleIP8JSObjectEENS2_IPN2js5ShapeEEENS1_13MutableHandleINS1_5ValueEEE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.cpp:1614
  18:          0x196533d - ZN2js17NativeGetPropertyEP9JSContextN2JS6HandleIPNS_12NativeObjectEEENS3_IP8JSObjectEENS3_I4jsidEENS2_13MutableHandleINS2_5ValueEEE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.cpp:1661
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.cpp:1878
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.cpp:1912
  19:          0x1b1616b - Z23JS_ForwardGetPropertyToP9JSContextN2JS6HandleIP8JSObjectEENS2_I4jsidEES5_NS1_13MutableHandleINS1_5ValueEEE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.h:1434
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:2788
  20:           0xc23547 - dom::bindings::utils::get_property_on_prototype::h9cbf69a55aeef12df8f
  21:           0x795270 - dom::bindings::codegen::Bindings::CSSStyleDeclarationBinding::get::he24ef5395f413f75mFB
  22:          0x22c9e4a - ZNK22ForwardingProxyHandler3getEP9JSContextN2JS6HandleIP8JSObjectEES6_NS3_I4jsidEENS2_13MutableHandleINS2_5ValueEEE
  23:          0x1bbf08f - ZN2js5Proxy3getEP9JSContextN2JS6HandleIP8JSObjectEES7_NS4_I4jsidEENS3_13MutableHandleINS3_5ValueEEE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/proxy/Proxy.cpp:286
  24:          0x1bbf1e6 - ZN2js17proxy_GetPropertyEP9JSContextN2JS6HandleIP8JSObjectEES6_NS3_I4jsidEENS2_13MutableHandleINS2_5ValueEEE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/proxy/Proxy.cpp:585
  25:          0x21b47b4 - ZN2js11GetPropertyEP9JSContextN2JS6HandleIP8JSObjectEES6_NS3_I4jsidEENS2_13MutableHandleINS2_5ValueEEE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/NativeObject.h:1433
  26:          0x1940add - ZL9InterpretP9JSContextRN2js8RunStateE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:260
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:2426
  27:          0x1946eb7 - ZN2js9RunScriptEP9JSContextRNS_8RunStateE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:452
  28:          0x194c200 - ZN2js13ExecuteKernelEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectRKNS2_5ValueENS_11ExecuteTypeENS_16AbstractFramePtrEPS9_
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:660
  29:          0x194dabb - ZN2js7ExecuteEP9JSContextN2JS6HandleIP8JSScriptEER8JSObjectPNS2_5ValueE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/vm/Interpreter.cpp:703
  30:          0x1b1c910 - ZL8EvaluateP9JSContextN2JS6HandleIP8JSObjectEERKNS1_22ReadOnlyCompileOptionsERNS1_18SourceBufferHolderENS1_13MutableHandleINS1_5ValueEEE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4185
  31:          0x1b1cc35 - ZN2JS8EvaluateEP9JSContextRKNS_22ReadOnlyCompileOptionsEPKDsyNS_13MutableHandleINS_5ValueEEE
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4219
                        at C:/msys64/home/Jason/servo/.cargo/git/checkouts/mozjs-06d7f04b6dbb8a8e/master/mozjs/js/src/jsapi.cpp:4273
  32:           0x94ec50 - dom::window::_&'a T.ScriptHelpers::evaluate_script_on_global_with_result::h16145906458933410978
  33:           0xa36fa6 - dom::htmlscriptelement::HTMLScriptElement::execute::ha89517dd88e1f739kv6
  34:           0xb75ee2 - dom::document::Document::finish_load::h08303258291a25faBFO
  35:           0xa2aa58 - dom::htmlscriptelement::ScriptContext.AsyncResponseListener::response_complete::h686034e1fa842466kj6
  36:          0x15873c3 - ResponseAction::process::h4df13f40ed10b5c5Ypf
  37:           0xa2e836 - network_listener::ListenerRunnable<T>.Runnable::handler::h6558691345236237746
  38:           0x8b4fed - script_thread::ScriptThread::handle_msg_from_script::hc1049ea3bb6ff391fBt
  39:           0x915d25 - script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::closure.197724
  40:           0x8ff1a3 - script_thread::ScriptThread::handle_msgs::h4330b1f6deb6c722Tmt
  41:           0x89ade7 - sys_common::unwind::try::try_fn::h7383399210879610963
  42:          0x2110f1a - sys_common::unwind::inner_try::h77626a58c53b5bb4TOt
  43:           0x89c267 - boxed::F.FnBox<A>::call_box::h14264557780924633441
  44:          0x211c499 - sys::thread::Thread::new::thread_start::h7d995f17b3b89feeazz
  45:     0x7ff859082d91 - GLOBAL__sub_I__ZN15GrGLConicEffectC2ERK22GrBackendEffectFactoryRK12GrDrawEffect
thread 'ScriptThread PipelineId { namespace_id: PipelineNamespaceId(0), index: PipelineIndex(0) }' panicked at 'assertion failed: *self.stack == mem::transmute(&*self)', C:/msys64/home/Jason/servo/.cargo\git\checkouts\rust-mozjs-ebb4917e843c0a11\master\src\rust.rs:334
stack backtrace:
   0:          0x211f00a - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43536
   1:          0x211e53e - panicking::default_handler::hcbd606cfbd8bf50bKsA
   2:          0x20e1bef - sys_common::unwind::begin_unwind_inner::hbdeeb049085a1e58RRt
   3:          0x20e31eb - sys_common::unwind::begin_unwind_fmt::h6f77f0426d82c98bXQt
   4:          0x2110ff2 - rust_begin_unwind
   5:          0x21335e8 - panicking::panic_fmt::h769e276b1a4fb549FRL
   6:           0xfdb3b2 - result::unwrap_failed::h10543326818038586143
   7:           0xfd39b4 - paint_thread::PaintThread<C>::start::h1829662992991079968
   8:           0xfc5eb9 - sys_common::unwind::try::try_fn::h15979825060268437803
   9:          0x2110f1a - sys_common::unwind::inner_try::h77626a58c53b5bb4TOt
  10:           0xfc6afa - boxed::F.FnBox<A>::call_box::h11577006902892480913
  11:          0x211c499 - sys::thread::Thread::new::thread_start::h7d995f17b3b89feeazz
  12:     0x7ff859082d91 - GLOBAL__sub_I__ZN15GrGLConicEffectC2ERK22GrBackendEffectFactoryRK12GrDrawEffect
thread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore\result.rs:746
thread 'PaintWorkerthread 'PaintWorker' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore\result.rs:746
' panicked at 'called `Result::unwrap()` on an `Err` value: RecvError', ../src/libcore\result.rs:746
stack backtrace:
   0:          0x211f00a - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43536
   1:          0x211e53e - panicking::default_handler::hcbd606cfbd8bf50bKsA
   2:          0x20e1bef - sys_common::unwind::begin_unwind_inner::hbdeeb049085a1e58RRt
   3:          0x20e31eb - sys_common::unwind::begin_unwind_fmt::h6f77f0426d82c98bXQt
   4:          0x2110ff2 - rust_begin_unwind
   5:          0x21335e8 - panicking::panic_fmt::h769e276b1a4fb549FRL
   6:           0x5dade2 - result::unwrap_failed::h8397378626604524438
   7:           0x5da09b - sys_common::unwind::try::try_fn::h14116229264620766606
   8:          0x2110f1a - sys_common::unwind::inner_try::h77626a58c53b5bb4TOt
   9:           0x5daa08 - boxed::F.FnBox<A>::call_box::h13085838289927279001
  10:          0x211c499 - sys::thread::Thread::new::thread_start::h7d995f17b3b89feeazz
  11:     0x7ff859082d91 - GLOBAL__sub_I__ZN15GrGLConicEffectC2ERK22GrBackendEffectFactoryRK12GrDrawEffect
stack backtrace:
   0:          0x211f00a - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43536
   1:          0x211e53e - panicking::default_handler::hcbd606cfbd8bf50bKsA
   2:          0x20e1bef - sys_common::unwind::begin_unwind_inner::hbdeeb049085a1e58RRt
   3:          0x20e31eb - sys_common::unwind::begin_unwind_fmt::h6f77f0426d82c98bXQt
   4:          0x2110ff2 - rust_begin_unwind
   5:          0x21335e8 - panicking::panic_fmt::h769e276b1a4fb549FRL
   6:           0x5dade2 - result::unwrap_failed::h8397378626604524438
   7:           0x5da09b - sys_common::unwind::try::try_fn::h14116229264620766606
   8:          0x2110f1a - sys_common::unwind::inner_try::h77626a58c53b5bb4TOt
   9:           0x5daa08 - boxed::F.FnBox<A>::call_box::h13085838289927279001
  10:          0x211c499 - sys::thread::Thread::new::thread_start::h7d995f17b3b89feeazz
  11:     0x7ff859082d91 - GLOBAL__sub_I__ZN15GrGLConicEffectC2ERK22GrBackendEffectFactoryRK12GrDrawEffect
stack backtrace:
   0:          0x211f00a - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43536
   1:          0x211e53e - panicking::default_handler::hcbd606cfbd8bf50bKsA
   2:          0x20e1bef - sys_common::unwind::begin_unwind_inner::hbdeeb049085a1e58RRt
   3:          0x20e31eb - sys_common::unwind::begin_unwind_fmt::h6f77f0426d82c98bXQt
   4:          0x2110ff2 - rust_begin_unwind
   5:          0x21335e8 - panicking::panic_fmt::h769e276b1a4fb549FRL
   6:           0x5dade2 - result::unwrap_failed::h8397378626604524438
   7:           0x5da09b - sys_common::unwind::try::try_fn::h14116229264620766606
   8:          0x2110f1a - sys_common::unwind::inner_try::h77626a58c53b5bb4TOt
   9:           0x5daa08 - boxed::F.FnBox<A>::call_box::h13085838289927279001
  10:          0x211c499 - sys::thread::Thread::new::thread_start::h7d995f17b3b89feeazz
  11:     0x7ff859082d91 - GLOBAL__sub_I__ZN15GrGLConicEffectC2ERK22GrBackendEffectFactoryRK12GrDrawEffect
stack backtrace:
   0:          0x211f00a - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43536
   1:          0x211e53e - panicking::default_handler::hcbd606cfbd8bf50bKsA
   2:          0x20e1bef - sys_common::unwind::begin_unwind_inner::hbdeeb049085a1e58RRt
   3:          0x20e31eb - sys_common::unwind::begin_unwind_fmt::h6f77f0426d82c98bXQt
   4:          0x2110ff2 - rust_begin_unwind
   5:          0x21335e8 - panicking::panic_fmt::h769e276b1a4fb549FRL
   6:          0x2154074 - option::expect_failed::h9c786e256c8d339fLpO
   7:           0x54277f - constellation::Constellation<LTF, STF>::handle_failure_msg::h9117242117905411941
   8:           0x4bf227 - constellation::Constellation<LTF, STF>::handle_request::h16358764878453514433
   9:           0x4b5f7c - sys_common::unwind::try::try_fn::h14897761701504641921
  10:          0x2110f1a - sys_common::unwind::inner_try::h77626a58c53b5bb4TOt
  11:           0x4b7b4a - boxed::F.FnBox<A>::call_box::h8753806614732775231
  12:          0x211c499 - sys::thread::Thread::new::thread_start::h7d995f17b3b89feeazz
  13:     0x7ff859082d91 - GLOBAL__sub_I__ZN15GrGLConicEffectC2ERK22GrBackendEffectFactoryRK12GrDrawEffect
stack backtrace:
   0:          0x211f00a - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43536
   1:          0x211e53e - panicking::default_handler::hcbd606cfbd8bf50bKsA
   2:          0x20e1bef - sys_common::unwind::begin_unwind_inner::hbdeeb049085a1e58RRt
   3:           0xc09393 - sys_common::unwind::begin_unwind::h8807528547972992131
   4:           0xc0aeda - js..jsapi_windows_gcc_64..Rooted<js..jsapi_windows_gcc_64..Value>::drop.148890::h0b3b7a04dc78addb
   5:           0xa37464 - dom::htmlscriptelement::HTMLScriptElement::execute::ha89517dd88e1f739kv6
   6:           0xb75ee2 - dom::document::Document::finish_load::h08303258291a25faBFO
   7:           0xa2aa58 - dom::htmlscriptelement::ScriptContext.AsyncResponseListener::response_complete::h686034e1fa842466kj6
   8:          0x15873c3 - ResponseAction::process::h4df13f40ed10b5c5Ypf
   9:           0xa2e836 - network_listener::ListenerRunnable<T>.Runnable::handler::h6558691345236237746
  10:           0x8b4fed - script_thread::ScriptThread::handle_msg_from_script::hc1049ea3bb6ff391fBt
  11:           0x915d25 - script_thread::ScriptThread::handle_msgs::_$u7b$$u7b$closure$u7d$$u7d$::closure.197724
  12:           0x8ff1a3 - script_thread::ScriptThread::handle_msgs::h4330b1f6deb6c722Tmt
  13:           0x89ade7 - sys_common::unwind::try::try_fn::h7383399210879610963
  14:          0x2110f1a - sys_common::unwind::inner_try::h77626a58c53b5bb4TOt
  15:           0x89c267 - boxed::F.FnBox<A>::call_box::h14264557780924633441
  16:          0x211c499 - sys::thread::Thread::new::thread_start::h7d995f17b3b89feeazz
  17:     0x7ff859082d91 - GLOBAL__sub_I__ZN15GrGLConicEffectC2ERK22GrBackendEffectFactoryRK12GrDrawEffect
thread panicked while panicking. aborting.
Servo exited with return value -4
```

**Comment by paulrouget** [comment] 2016-03-29 00:52
Dupe of https://github.com/servo/servo/issues/10243

**Closed by paulrouget** 2016-03-29 00:52 UTC
