### ISSUE TITLE
XHR mozSystem isn't supported by servo

### ISSUE THREAD

**Issue by Gozala** [browserhtml/browserhtml#866] opened 2016-02-08 20:03 UTC
Servo does not support [mozSystem](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#mozSystem) property on XHR that blocks #863 as duckduckgo does not set CORS headers and servo fails requests.

@paulrouget should I move this bug to servo ? I was hesitant as it's custom extension to XHR that probably belongs to realm of servo based graphene or elsewhere. Anyway I'll let you decide where this bug should live.

Also here is test I end up creating that may come handy:

```html
<html>
<body>Initializing...</body>
<script>
const request = new XMLHttpRequest({ mozSystem: true });
const uri = 'http://ac.duckduckgo.com/ac/?q=servo&type=list'
document.body.textContent = `Requesting ${uri}`
request.open('GET', uri, true);
request.send();
request.onerror = event =>
  document.body.textContent = `Failed: "${event.target.statusText}" - ${event.target.status}`
request.onload = event =>
  document.body.textContent = `Loaded: ${event.target.response}`
</script>
</html>
```

**Comment by Manishearth** [comment] 2016-02-14 01:33
Is graphene specced anywhere?  The readme says "Graphene: a runtime for building native apps in HTML. It's currently in development and part of Servo.", however I can't find a concrete part of Servo that deals with this aside from the code handling `<iframe mozbrowser>`.

**Comment by paulrouget** [comment] 2016-02-15 03:02
> Is graphene specced anywhere? The readme says "Graphene: a runtime for building native apps in HTML. It's currently in development and part of Servo.", however I can't find a concrete part of Servo that deals with this aside from the code handling <iframe mozbrowser>.

That's basically it for now. More context: https://github.com/servo/servo/issues/7379

> Also, though the ship has probably sailed on this, I'd personally prefer if nonstandard extensions that are useful for Graphene be centralized in a single interface as much as possible; e.g. Graphene.createSystemXHR(...) instead of new XMLHttpRequest({mozSystem: true}}

Agreed. This is a thing that will be discussed soon at our next servo/bhtml meeting.

**Comment by paulrouget** [comment] 2016-02-19 17:56
I disabled cross-origin checks in our servo nightly builds.

**Comment by paulrouget** [comment] 2016-03-21 18:45
Closing. Dupe of https://github.com/servo/servo/issues/9582.

**Closed by paulrouget** 2016-03-21 18:45 UTC
Labels: P1
