### ISSUE TITLE
releasing forcetouch closes the sidebar

### ISSUE THREAD

**Issue by paulrouget** [browserhtml/browserhtml#1038] opened 2016-05-17 02:34 UTC

**Comment by paulrouget** [comment] 2016-05-18 06:39
This happens because we get a click on the overlay when it's released.

**Comment by paulrouget** [comment] 2016-05-18 07:01
This doesn't always happen because of a bug in Servo where the iframe get the mouse events before the overlay. See https://github.com/servo/servo/issues/11108

**Comment by Gozala** [comment] 2016-06-01 18:04
@paulrouget It is assigned to you, does that mean you're going to fix it ? Also should it be a P2 instead ?

**Comment by Gozala** [comment] 2016-06-07 18:08
This seems to be caused by servo/servo#11664 @paulrouget do you think it can be fixed in servo or should we come up with a workaround ?

**Comment by Gozala** [comment] 2016-06-07 18:33
Create a workaround #1087 that is not so bad & avoids the issue described here.

**Comment by Gozala** [comment] 2016-08-17 22:36
was fixed by #1087

**Closed by Gozala** 2016-08-17 22:36 UTC
Labels: P1
