### ISSUE TITLE
Can't move cursor in URL while page is loading

### ISSUE THREAD

**Issue by ConnorGBrewster** [browserhtml/browserhtml#1223] opened 2016-08-06 16:23 UTC
If you select the URL in the URL bar, and use the arrows to try to move the cursor, the text will deselect and reselect quickly. Which makes it so you cannot move the cursor to one side or the other of the URL.

**Comment by Gozala** [comment] 2016-08-08 18:08
@ConnorGBrewster could you please post specific steps to reproduce, I am not sure I understand what you were describing.

**Comment by ConnorGBrewster** [comment] 2016-08-08 20:01
Steps:
1. click on hacker news on newtab page
2. close the tab and click on github on newtab
3. Select the URL bar and use the arrow keys

**Comment by Gozala** [comment] 2016-08-12 20:27
At this point we crash reporter prompt on step 3,  so I'm inclined to thing that cursor movement is due to panic! Closing this for now, lets reopen after #1224 is fixed if it will still appear broken.

**Closed by Gozala** 2016-08-12 20:27 UTC
